#-------------------------------------------------------------------------#
#-------------------------- TOBIAS input data ----------------------------#
#-------------------------------------------------------------------------#

data:
  hio: ['data/bam/SRR10461989_hio_rep02_R1.bam',
         'data/bam/SRR10461988_hio_rep01_R1.bam']                          
  
run_info:
  organism: human                           #mouse/human
  fasta: /media/ag-cherrmann/aquintero/pipelines/pipelines-ATACseq/db/iGenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa                               #.fasta-file containing organism genome
  blacklist: /media/ag-cherrmann/lcosta/miniconda/Blacklist/lists/hg38-blacklist.v2.bed       #.bed-file containing blacklisted regions
  gtf:  /media/ag-cherrmann/tranff/dlTADs/data/K562/gencode.v35.annotation.gtf
  motifs: /media/ag-cherrmann/cramirez/TOBIAS_snakemake/data/motifs/*
  output: output_one_sample                       #output directory 



#-------------------------------------------------------------------------#
#----------------------- Default module parameters -----------------------#
#-------------------------------------------------------------------------#

macs: "--nomodel --shift -100 --extsize 200 --broad"
atacorrect: ""
footprinting: ""
bindetect: ""
